#include "impl_internal.h"

#include "assert.h"
#include "stdlib.h"
#include "string.h"

// BEGIN GENERATED: EMPATHY BYTECODE TABLES
// Generated by tools/generate_bytecode.py. Do not edit manually.
static const uint8_t impl_bytecode_instruction_sizes[EMPATHY_BYTECODE_OP_ENUM_MAX] =
{
	2, 3, 5, 9, 2, 3, 5, 9, 5, 9, 9, 5,
	5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 9, 9, 9, 1, 1, 1, 1, 2, 3, 5, 9,
	2, 3, 5, 9, 5, 9, 9, 1, 1, 1, 1, 5,
	1,
};

static const uint8_t impl_bytecode_instruction_modes[EMPATHY_BYTECODE_OP_ENUM_MAX] =
{
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1,
};
// END GENERATED: EMPATHY BYTECODE TABLES

static EMPATHY_INLINE uint64_t impl_bytecodeGetBaseTypeSize(Empathy_ValueBaseType base_type)
{
	switch (base_type)
	{
		case EMPATHY_VALUE_BASE_TYPE_UINT8:
		case EMPATHY_VALUE_BASE_TYPE_INT8: return 1;

		case EMPATHY_VALUE_BASE_TYPE_UINT16:
		case EMPATHY_VALUE_BASE_TYPE_INT16: return 2;

		case EMPATHY_VALUE_BASE_TYPE_UINT32:
		case EMPATHY_VALUE_BASE_TYPE_INT32:
		case EMPATHY_VALUE_BASE_TYPE_FLOAT32: return 4;

		case EMPATHY_VALUE_BASE_TYPE_UINT64:
		case EMPATHY_VALUE_BASE_TYPE_INT64:
		case EMPATHY_VALUE_BASE_TYPE_FLOAT64:
		case EMPATHY_VALUE_BASE_TYPE_ATOM: return 8;

		default: assert(0); return UINT64_MAX;
	}
}

static EMPATHY_INLINE uint8_t impl_bytecodeReadU8(const uint8_t *data)
{
	return data[0];
}

static EMPATHY_INLINE uint16_t impl_bytecodeReadU16(const uint8_t *data)
{
	return
		((uint16_t)data[0] << 0u) |
		((uint16_t)data[1] << 8u);
}

static EMPATHY_INLINE uint32_t impl_bytecodeReadU32(const uint8_t *data)
{
	return
		((uint32_t)data[0] << 0u) |
		((uint32_t)data[1] << 8u) |
		((uint32_t)data[2] << 16u) |
		((uint32_t)data[3] << 24u);
}

static EMPATHY_INLINE uint64_t impl_bytecodeReadU64(const uint8_t *data)
{
	return
		((uint64_t)data[0] << 0u) |
		((uint64_t)data[1] << 8u) |
		((uint64_t)data[2] << 16u) |
		((uint64_t)data[3] << 24u) |
		((uint64_t)data[4] << 32u) |
		((uint64_t)data[5] << 40u) |
		((uint64_t)data[6] << 48u) |
		((uint64_t)data[7] << 56u);
}

static EMPATHY_INLINE int8_t impl_bytecodeReadI8(const uint8_t *data)
{
	int8_t value = 0;
	memcpy(&value, data, sizeof(value));
	return value;
}

static EMPATHY_INLINE int16_t impl_bytecodeReadI16(const uint8_t *data)
{
	uint16_t bits = impl_bytecodeReadU16(data);
	int16_t value = 0;
	memcpy(&value, &bits, sizeof(value));
	return value;
}

static EMPATHY_INLINE int32_t impl_bytecodeReadI32(const uint8_t *data)
{
	uint32_t bits = impl_bytecodeReadU32(data);
	int32_t value = 0;
	memcpy(&value, &bits, sizeof(value));
	return value;
}

static EMPATHY_INLINE int64_t impl_bytecodeReadI64(const uint8_t *data)
{
	uint64_t bits = impl_bytecodeReadU64(data);
	int64_t value = 0;
	memcpy(&value, &bits, sizeof(value));
	return value;
}

static EMPATHY_INLINE float impl_bytecodeReadF32(const uint8_t *data)
{
	uint32_t bits = impl_bytecodeReadU32(data);
	float value = 0.0f;
	assert(sizeof(value) == sizeof(bits));
	memcpy(&value, &bits, sizeof(bits));
	return value;
}

static EMPATHY_INLINE double impl_bytecodeReadF64(const uint8_t *data)
{
	uint64_t bits = impl_bytecodeReadU64(data);
	double value = 0.0;
	assert(sizeof(value) == sizeof(bits));
	memcpy(&value, &bits, sizeof(bits));
	return value;
}

static EMPATHY_INLINE Empathy_Atom impl_bytecodeReadAtom(const uint8_t *data)
{
	Empathy_Atom atom = {0};
	atom.type = impl_bytecodeReadU32(data);
	atom.value = impl_bytecodeReadU32(data + 4);
	return atom;
}

static EMPATHY_INLINE uint64_t impl_bytecodeGetInstructionSize(Empathy_BytecodeOpcode opcode)
{
	assert((uint32_t)opcode < EMPATHY_BYTECODE_OP_ENUM_MAX);
	return impl_bytecode_instruction_sizes[opcode];
}

static EMPATHY_INLINE Impl_OpcodeMode impl_bytecodeGetInstructionMode(Empathy_BytecodeOpcode opcode)
{
	assert((uint32_t)opcode < EMPATHY_BYTECODE_OP_ENUM_MAX);
	return (Impl_OpcodeMode)impl_bytecode_instruction_modes[opcode];
}

static EMPATHY_INLINE int impl_bytecodeValidateAtom(const Impl_ProgramLayout *layout, Empathy_Atom atom)
{
	for (uint32_t i = 0; i < layout->num_atom_types; ++i)
	{
		const Impl_ProgramLayoutAtomType *atom_type = &layout->atom_types[i];
		if (atom_type->type == atom.type)
			return atom.value >= atom_type->min_value && atom.value <= atom_type->max_value;
	}

	return 0;
}

Empathy_Result impl_bytecodeValidate(const Empathy_ProgramDesc *program_desc, const Impl_ProgramLayout *layout)
{
	assert(program_desc);
	assert(program_desc->entry_points);
	assert(program_desc->num_entry_points > 0);
	assert(program_desc->bytecode_size > 0);
	assert(program_desc->bytecode_data);
	assert(layout);

	if (program_desc->bytecode_version != EMPATHY_BYTECODE_VERSION)
		return EMPATHY_UNSUPPORTED_BYTECODE_VERSION;

	const uint64_t size = program_desc->bytecode_size;
	const uint8_t *bytes = (const uint8_t *)program_desc->bytecode_data;

	uint8_t *modes = (uint8_t *)malloc(sizeof(uint8_t) * program_desc->bytecode_size);
	memset(modes, 0, sizeof(uint8_t) * program_desc->bytecode_size);
	assert(modes);

	Empathy_Result result = EMPATHY_SUCCESS;
	uint64_t offset = 0;
	while (offset < size)
	{
		uint8_t opcode_data = bytes[offset];
		if (opcode_data >= EMPATHY_BYTECODE_OP_ENUM_MAX)
		{
			result = EMPATHY_INVALID_INSTRUCTION_OPCODE;
			break;
		}

		Empathy_BytecodeOpcode opcode = (Empathy_BytecodeOpcode)opcode_data;
		uint64_t instruction_size = impl_bytecodeGetInstructionSize(opcode);
		if (instruction_size > size - offset)
		{
			result = EMPATHY_INVALID_INSTRUCTION_OPCODE;
			break;
		}

		modes[offset] = (uint8_t)impl_bytecodeGetInstructionMode(opcode);
		offset += instruction_size;
	}

	offset = 0;
	while (result == EMPATHY_SUCCESS && offset < size)
	{
		Empathy_BytecodeOpcode opcode = (Empathy_BytecodeOpcode)bytes[offset];
		const uint8_t *instruction_data = bytes + offset + 1;

		switch (opcode)
		{
			case EMPATHY_BYTECODE_OP_PUSH_ATOM:
			case EMPATHY_BYTECODE_OP_YIELD_PUSH_ATOM:
			{
				if (!impl_bytecodeValidateAtom(layout, impl_bytecodeReadAtom(instruction_data)))
					result = EMPATHY_INVALID_INSTRUCTION_DATA;
			}
			break;

			case EMPATHY_BYTECODE_OP_LOAD:
			case EMPATHY_BYTECODE_OP_STORE:
			{
				if (impl_bytecodeReadU32(instruction_data) >= layout->num_parameters)
					result = EMPATHY_INVALID_INSTRUCTION_DATA;
			}
			break;

			case EMPATHY_BYTECODE_OP_JUMP:
			case EMPATHY_BYTECODE_OP_JUMP_FALSE:
			case EMPATHY_BYTECODE_OP_JUMP_TRUE:
			{
				uint64_t target = impl_bytecodeReadU64(instruction_data);
				if (target >= size || modes[target] == 0)
					result = EMPATHY_INVALID_INSTRUCTION_DATA;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD:
				if (impl_bytecodeReadU32(instruction_data) >= layout->num_yields)
					result = EMPATHY_INVALID_INSTRUCTION_DATA;
				break;

			default: break;
		}

		offset += impl_bytecodeGetInstructionSize(opcode);
	}

	for (uint32_t i = 0; result == EMPATHY_SUCCESS && i < program_desc->num_entry_points; ++i)
	{
		uint64_t execution_offset = program_desc->entry_points[i].execution_offset;
		uint64_t predicate_offset = program_desc->entry_points[i].predicate_offset;

		if (execution_offset >= size || (modes[execution_offset] & IMPL_OPCODE_MODE_EXECUTION) == 0)
		{
			result = EMPATHY_INVALID_INSTRUCTION_DATA;
			break;
		}

		if (predicate_offset != EMPATHY_PROGRAM_OFFSET_NONE &&
			(predicate_offset >= size || (modes[predicate_offset] & IMPL_OPCODE_MODE_PREDICATE) == 0))
		{
			result = EMPATHY_INVALID_INSTRUCTION_DATA;
		}
	}

	free(modes);
	return result;
}

Empathy_Result impl_bytecodeExecute(Impl_ExecutionContext *context, uint32_t instruction_limit)
{
	assert(context);

	const Impl_Program *program = context->program;
	assert(program);
	assert(program->data);
	assert(program->size > 0);

	const Impl_ProgramLayout *layout = context->layout;
	assert(layout);

	Impl_MachineStack *stack = &context->execution.stack;
	assert(stack);
	assert(stack->data);
	assert(stack->size > 0);
	assert(stack->head <= stack->size);

	Impl_MachineStack *yield = &context->yield.stack;
	assert(yield);
	assert(yield->data);
	assert(yield->size > 0);
	assert(yield->head <= yield->size);

	const uint8_t *bytes = (const uint8_t *)program->data;

	for (uint32_t current_instruction = 0; current_instruction < instruction_limit; ++current_instruction)
	{
		if (context->execution.instruction_pointer >= program->size)
			return EMPATHY_PROGRAM_OUT_OF_BOUNDS_READ;

		uint8_t opcode_data = bytes[context->execution.instruction_pointer];

		if (opcode_data >= EMPATHY_BYTECODE_OP_ENUM_MAX)
			return EMPATHY_INVALID_INSTRUCTION_OPCODE;

		Empathy_BytecodeOpcode opcode = (Empathy_BytecodeOpcode)opcode_data;

		uint64_t instruction_size = impl_bytecodeGetInstructionSize(opcode);
		if (context->execution.instruction_pointer + instruction_size > program->size)
			return EMPATHY_INVALID_INSTRUCTION_OPCODE;

		Impl_OpcodeMode mode = impl_bytecodeGetInstructionMode(opcode);
		if ((mode & context->mode) == 0)
			return EMPATHY_INVALID_INSTRUCTION_OPCODE;

		const uint8_t *instruction_data = bytes + context->execution.instruction_pointer + 1;

		switch (opcode)
		{
			case EMPATHY_BYTECODE_OP_PUSH_U8:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				uint8_t data = impl_bytecodeReadU8(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT8;
				value.data.u8 = data;

				stack->data[stack->head++] = value;
			}
			break;
			
			case EMPATHY_BYTECODE_OP_PUSH_U16:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				uint16_t data = impl_bytecodeReadU16(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT16;
				value.data.u16 = data;

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_PUSH_U32:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				uint32_t data = impl_bytecodeReadU32(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT32;
				value.data.u32 = data;

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_PUSH_U64:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				uint64_t data = impl_bytecodeReadU64(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT64;
				value.data.u64 = data;

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_PUSH_I8:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				int8_t data = impl_bytecodeReadI8(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_INT8;
				value.data.i8 = data;

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_PUSH_I16:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				int16_t data = impl_bytecodeReadI16(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_INT16;
				value.data.i16 = data;

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_PUSH_I32:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				int32_t data = impl_bytecodeReadI32(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_INT32;
				value.data.i32 = data;

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_PUSH_I64:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				int64_t data = impl_bytecodeReadI64(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_INT64;
				value.data.i64 = data;

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_PUSH_F32:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				float data = impl_bytecodeReadF32(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_FLOAT32;
				value.data.f32 = data;

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_PUSH_F64:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				double data = impl_bytecodeReadF64(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_FLOAT64;
				value.data.f64 = data;

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_PUSH_ATOM:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				Empathy_Atom data = impl_bytecodeReadAtom(instruction_data);

				Empathy_Value value = {0};
				value.type = (Empathy_ValueType){EMPATHY_VALUE_BASE_TYPE_ATOM, data.type};
				value.data.atom = data;

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_LOAD:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				uint32_t index = impl_bytecodeReadU32(instruction_data);
				assert(index < layout->num_parameters);

				const Impl_ProgramLayoutParameter *parameter = &layout->parameters[index];
				assert(parameter);

				if ((parameter->access & EMPATHY_PARAMETER_ACCESS_FLAGS_READ) == 0)
					return EMPATHY_PARAMETER_NOT_READABLE;

				uint64_t parameter_offset = parameter->offset;
				uint64_t parameter_size = impl_bytecodeGetBaseTypeSize(parameter->type.base_type);

				assert(parameter->table < context->max_bindings);

				const uint8_t *table = (uint8_t *)context->bindings[parameter->table].data;
				const uint64_t table_size = context->bindings[parameter->table].size;
				assert(table);

				if (parameter_offset + parameter_size > table_size)
					return EMPATHY_PARAMETER_TABLE_OUT_OF_BOUNDS_READ;

				table += parameter_offset;

				Empathy_Value value = {0};
				value.type = parameter->type;

				switch (parameter->type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = *(const uint8_t *)table; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u16 = *(const uint16_t *)table; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u32 = *(const uint32_t *)table; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u64 = *(const uint64_t *)table; break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.i8 = *(const int8_t *)table; break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.i16 = *(const int16_t *)table; break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.i32 = *(const int32_t *)table; break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.i64 = *(const int64_t *)table; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.f32 = *(const float *)table; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.f64 = *(const double *)table; break;
					case EMPATHY_VALUE_BASE_TYPE_ATOM: value.data.atom = *(const Empathy_Atom *)table; break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_STORE:
			{
				if (stack->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				uint32_t index = impl_bytecodeReadU32(instruction_data);
				assert(index < layout->num_parameters);

				const Impl_ProgramLayoutParameter *parameter = &layout->parameters[index];
				assert(parameter);

				if ((parameter->access & EMPATHY_PARAMETER_ACCESS_FLAGS_WRITE) == 0)
					return EMPATHY_PARAMETER_NOT_WRITABLE;

				Empathy_Value value = stack->data[stack->head - 1];

				if (parameter->type.base_type != value.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				if (parameter->type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM && parameter->type.atom_type != value.type.atom_type)
					return EMPATHY_ATOM_TYPE_MISMATCH;

				uint64_t parameter_offset = parameter->offset;
				uint64_t parameter_size = impl_bytecodeGetBaseTypeSize(parameter->type.base_type);
				uint64_t value_size = impl_bytecodeGetBaseTypeSize(value.type.base_type);

				assert(value_size == parameter_size);
				assert(parameter->table < context->max_bindings);

				uint8_t *table = (uint8_t *)context->bindings[parameter->table].data;
				uint64_t table_size = context->bindings[parameter->table].size;
				assert(table);

				if (parameter_offset + parameter_size > table_size)
					return EMPATHY_PARAMETER_TABLE_OUT_OF_BOUNDS_WRITE;

				table += parameter_offset;

				switch (parameter->type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: *(uint8_t *)table = value.data.u8; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: *(uint16_t *)table = value.data.u16; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: *(uint32_t *)table = value.data.u32; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: *(uint64_t *)table = value.data.u64; break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: *(int8_t *)table = value.data.i8; break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: *(int16_t *)table = value.data.i16; break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: *(int32_t *)table = value.data.i32; break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: *(int64_t *)table = value.data.i64; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: *(float *)table = value.data.f32; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: *(double *)table = value.data.f64; break;
					case EMPATHY_VALUE_BASE_TYPE_ATOM: *(Empathy_Atom *)table = value.data.atom; break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 1;
			}
			break;

			case EMPATHY_BYTECODE_OP_DROP:
			{
				if (stack->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				stack->head--;
			}
			break;

			case EMPATHY_BYTECODE_OP_DUP:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				if (stack->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value value = stack->data[stack->head - 1];
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_ADD:
			{
				if (stack->head <= 1)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value b = stack->data[stack->head - 1];
				Empathy_Value a = stack->data[stack->head - 2];

				if (a.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (b.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (a.type.base_type != b.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				Empathy_Value value = {0};
				value.type = a.type;

				switch (value.type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = a.data.u8 + b.data.u8; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u16 = a.data.u16 + b.data.u16; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u32 = a.data.u32 + b.data.u32; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u64 = a.data.u64 + b.data.u64; break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.i8 = a.data.i8 + b.data.i8; break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.i16 = a.data.i16 + b.data.i16; break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.i32 = a.data.i32 + b.data.i32; break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.i64 = a.data.i64 + b.data.i64; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.f32 = a.data.f32 + b.data.f32; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.f64 = a.data.f64 + b.data.f64; break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 2;
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_SUB:
			{
				if (stack->head <= 1)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value b = stack->data[stack->head - 1];
				Empathy_Value a = stack->data[stack->head - 2];

				if (a.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (b.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (a.type.base_type != b.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				Empathy_Value value = {0};
				value.type = a.type;

				switch (value.type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = a.data.u8 - b.data.u8; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u16 = a.data.u16 - b.data.u16; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u32 = a.data.u32 - b.data.u32; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u64 = a.data.u64 - b.data.u64; break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.i8 = a.data.i8 - b.data.i8; break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.i16 = a.data.i16 - b.data.i16; break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.i32 = a.data.i32 - b.data.i32; break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.i64 = a.data.i64 - b.data.i64; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.f32 = a.data.f32 - b.data.f32; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.f64 = a.data.f64 - b.data.f64; break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 2;
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_MUL:
			{
				if (stack->head <= 1)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value b = stack->data[stack->head - 1];
				Empathy_Value a = stack->data[stack->head - 2];

				if (a.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (b.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (a.type.base_type != b.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				Empathy_Value value = {0};
				value.type = a.type;

				switch (value.type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = a.data.u8 * b.data.u8; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u16 = a.data.u16 * b.data.u16; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u32 = a.data.u32 * b.data.u32; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u64 = a.data.u64 * b.data.u64; break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.i8 = a.data.i8 * b.data.i8; break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.i16 = a.data.i16 * b.data.i16; break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.i32 = a.data.i32 * b.data.i32; break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.i64 = a.data.i64 * b.data.i64; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.f32 = a.data.f32 * b.data.f32; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.f64 = a.data.f64 * b.data.f64; break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 2;
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_DIV:
			{
				if (stack->head <= 1)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value b = stack->data[stack->head - 1];
				Empathy_Value a = stack->data[stack->head - 2];

				if (a.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (b.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (a.type.base_type != b.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				Empathy_Value value = {0};
				value.type = a.type;

				switch (value.type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = a.data.u8 / b.data.u8; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u16 = a.data.u16 / b.data.u16; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u32 = a.data.u32 / b.data.u32; break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u64 = a.data.u64 / b.data.u64; break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.i8 = a.data.i8 / b.data.i8; break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.i16 = a.data.i16 / b.data.i16; break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.i32 = a.data.i32 / b.data.i32; break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.i64 = a.data.i64 / b.data.i64; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.f32 = a.data.f32 / b.data.f32; break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.f64 = a.data.f64 / b.data.f64; break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 2;
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_EQUAL:
			{
				if (stack->head <= 1)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value b = stack->data[stack->head - 1];
				Empathy_Value a = stack->data[stack->head - 2];

				if (a.type.base_type != b.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				if (a.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM && a.type.atom_type != b.type.atom_type)
					return EMPATHY_ATOM_TYPE_MISMATCH;

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT8;

				switch (a.type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = (a.data.u8 == b.data.u8); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u8 = (a.data.u16 == b.data.u16); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u8 = (a.data.u32 == b.data.u32); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u8 = (a.data.u64 == b.data.u64); break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.u8 = (a.data.i8 == b.data.i8); break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.u8 = (a.data.i16 == b.data.i16); break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.u8 = (a.data.i32 == b.data.i32); break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.u8 = (a.data.i64 == b.data.i64); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.u8 = (a.data.f32 == b.data.f32); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.u8 = (a.data.f64 == b.data.f64); break;
					case EMPATHY_VALUE_BASE_TYPE_ATOM: value.data.u8 = (memcmp(&a.data.atom, &b.data.atom, sizeof(Empathy_Atom)) == 0); break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 2;
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_NOT_EQUAL:
			{
				if (stack->head <= 1)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value b = stack->data[stack->head - 1];
				Empathy_Value a = stack->data[stack->head - 2];

				if (a.type.base_type != b.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				if (a.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM && a.type.atom_type != b.type.atom_type)
					return EMPATHY_ATOM_TYPE_MISMATCH;

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT8;

				switch (a.type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = (a.data.u8 != b.data.u8); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u8 = (a.data.u16 != b.data.u16); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u8 = (a.data.u32 != b.data.u32); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u8 = (a.data.u64 != b.data.u64); break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.u8 = (a.data.i8 != b.data.i8); break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.u8 = (a.data.i16 != b.data.i16); break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.u8 = (a.data.i32 != b.data.i32); break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.u8 = (a.data.i64 != b.data.i64); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.u8 = (a.data.f32 != b.data.f32); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.u8 = (a.data.f64 != b.data.f64); break;
					case EMPATHY_VALUE_BASE_TYPE_ATOM: value.data.u8 = (memcmp(&a.data.atom, &b.data.atom, sizeof(Empathy_Atom)) != 0); break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 2;
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_LESS:
			{
				if (stack->head <= 1)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value b = stack->data[stack->head - 1];
				Empathy_Value a = stack->data[stack->head - 2];

				if (a.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (b.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (a.type.base_type != b.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT8;

				switch (a.type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = (a.data.u8 < b.data.u8); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u8 = (a.data.u16 < b.data.u16); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u8 = (a.data.u32 < b.data.u32); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u8 = (a.data.u64 < b.data.u64); break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.u8 = (a.data.i8 < b.data.i8); break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.u8 = (a.data.i16 < b.data.i16); break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.u8 = (a.data.i32 < b.data.i32); break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.u8 = (a.data.i64 < b.data.i64); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.u8 = (a.data.f32 < b.data.f32); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.u8 = (a.data.f64 < b.data.f64); break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 2;
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_LESS_EQUAL:
			{
				if (stack->head <= 1)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value b = stack->data[stack->head - 1];
				Empathy_Value a = stack->data[stack->head - 2];

				if (a.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (b.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (a.type.base_type != b.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT8;

				switch (a.type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = (a.data.u8 <= b.data.u8); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u8 = (a.data.u16 <= b.data.u16); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u8 = (a.data.u32 <= b.data.u32); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u8 = (a.data.u64 <= b.data.u64); break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.u8 = (a.data.i8 <= b.data.i8); break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.u8 = (a.data.i16 <= b.data.i16); break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.u8 = (a.data.i32 <= b.data.i32); break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.u8 = (a.data.i64 <= b.data.i64); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.u8 = (a.data.f32 <= b.data.f32); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.u8 = (a.data.f64 <= b.data.f64); break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 2;
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_GREATER:
			{
				if (stack->head <= 1)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value b = stack->data[stack->head - 1];
				Empathy_Value a = stack->data[stack->head - 2];

				if (a.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (b.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (a.type.base_type != b.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT8;

				switch (a.type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = (a.data.u8 > b.data.u8); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u8 = (a.data.u16 > b.data.u16); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u8 = (a.data.u32 > b.data.u32); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u8 = (a.data.u64 > b.data.u64); break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.u8 = (a.data.i8 > b.data.i8); break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.u8 = (a.data.i16 > b.data.i16); break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.u8 = (a.data.i32 > b.data.i32); break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.u8 = (a.data.i64 > b.data.i64); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.u8 = (a.data.f32 > b.data.f32); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.u8 = (a.data.f64 > b.data.f64); break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 2;
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_GREATER_EQUAL:
			{
				if (stack->head <= 1)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value b = stack->data[stack->head - 1];
				Empathy_Value a = stack->data[stack->head - 2];

				if (a.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (b.type.base_type == EMPATHY_VALUE_BASE_TYPE_ATOM)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (a.type.base_type != b.type.base_type)
					return EMPATHY_BASE_TYPE_MISMATCH;

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT8;

				switch (a.type.base_type)
				{
					case EMPATHY_VALUE_BASE_TYPE_UINT8: value.data.u8 = (a.data.u8 >= b.data.u8); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT16: value.data.u8 = (a.data.u16 >= b.data.u16); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT32: value.data.u8 = (a.data.u32 >= b.data.u32); break;
					case EMPATHY_VALUE_BASE_TYPE_UINT64: value.data.u8 = (a.data.u64 >= b.data.u64); break;
					case EMPATHY_VALUE_BASE_TYPE_INT8: value.data.u8 = (a.data.i8 >= b.data.i8); break;
					case EMPATHY_VALUE_BASE_TYPE_INT16: value.data.u8 = (a.data.i16 >= b.data.i16); break;
					case EMPATHY_VALUE_BASE_TYPE_INT32: value.data.u8 = (a.data.i32 >= b.data.i32); break;
					case EMPATHY_VALUE_BASE_TYPE_INT64: value.data.u8 = (a.data.i64 >= b.data.i64); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT32: value.data.u8 = (a.data.f32 >= b.data.f32); break;
					case EMPATHY_VALUE_BASE_TYPE_FLOAT64: value.data.u8 = (a.data.f64 >= b.data.f64); break;
					default: assert(0); return EMPATHY_INTERNAL_ERROR;
				}

				stack->head -= 2;
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_JUMP:
			{
				uint64_t jump_target = impl_bytecodeReadU64(instruction_data);
				if (jump_target >= program->size)
					return EMPATHY_INVALID_INSTRUCTION_DATA;

				context->execution.instruction_pointer = jump_target;
				instruction_size = 0;
			}
			break;

			case EMPATHY_BYTECODE_OP_JUMP_FALSE:
			{
				uint64_t jump_target = impl_bytecodeReadU64(instruction_data);
				if (jump_target >= program->size)
					return EMPATHY_INVALID_INSTRUCTION_DATA;

				if (stack->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value value = stack->data[stack->head - 1];
				if (value.type.base_type != EMPATHY_VALUE_BASE_TYPE_UINT8)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (value.data.u8 == 0)
				{
					context->execution.instruction_pointer = jump_target;
					instruction_size = 0;
				}

				stack->head -= 1;
			}
			break;

			case EMPATHY_BYTECODE_OP_JUMP_TRUE:
			{
				uint64_t jump_target = impl_bytecodeReadU64(instruction_data);
				if (jump_target >= program->size)
					return EMPATHY_INVALID_INSTRUCTION_DATA;

				if (stack->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value value = stack->data[stack->head - 1];
				if (value.type.base_type != EMPATHY_VALUE_BASE_TYPE_UINT8)
					return EMPATHY_INVALID_OPERAND_TYPE;

				if (value.data.u8 != 0)
				{
					context->execution.instruction_pointer = jump_target;
					instruction_size = 0;
				}

				stack->head -= 1;
			}
			break;

			case EMPATHY_BYTECODE_OP_REJECT:
			{
				context->execution.instruction_pointer += instruction_size;
				return EMPATHY_PREDICATE_REJECTED;
			}
			break;

			case EMPATHY_BYTECODE_OP_REJECT_FALSE:
			{
				if (stack->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value value = stack->data[stack->head - 1];
				if (value.type.base_type != EMPATHY_VALUE_BASE_TYPE_UINT8)
					return EMPATHY_INVALID_OPERAND_TYPE;

				stack->head -= 1;

				if (value.data.u8 == 0)
				{
					context->execution.instruction_pointer += instruction_size;
					return EMPATHY_PREDICATE_REJECTED;
				}
			}
			break;

			case EMPATHY_BYTECODE_OP_REJECT_TRUE:
			{
				if (stack->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value value = stack->data[stack->head - 1];
				if (value.type.base_type != EMPATHY_VALUE_BASE_TYPE_UINT8)
					return EMPATHY_INVALID_OPERAND_TYPE;

				stack->head -= 1;

				if (value.data.u8 != 0)
				{
					context->execution.instruction_pointer += instruction_size;
					return EMPATHY_PREDICATE_REJECTED;
				}
			}
			break;

			case EMPATHY_BYTECODE_OP_MATCH:
			{
				if (stack->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				context->execution.instruction_pointer += instruction_size;
				return EMPATHY_PREDICATE_MATCHED;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUSH_U8:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				uint8_t data = impl_bytecodeReadU8(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT8;
				value.data.u8 = data;

				yield->data[yield->head++] = value;
			}
			break;
			
			case EMPATHY_BYTECODE_OP_YIELD_PUSH_U16:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				uint16_t data = impl_bytecodeReadU16(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT16;
				value.data.u16 = data;

				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUSH_U32:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				uint32_t data = impl_bytecodeReadU32(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT32;
				value.data.u32 = data;


				yield->data[yield->head++] = value;

			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUSH_U64:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				uint64_t data = impl_bytecodeReadU64(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_UINT64;
				value.data.u64 = data;

				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUSH_I8:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				int8_t data = impl_bytecodeReadI8(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_INT8;
				value.data.i8 = data;

				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUSH_I16:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				int16_t data = impl_bytecodeReadI16(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_INT16;
				value.data.i16 = data;

				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUSH_I32:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				int32_t data = impl_bytecodeReadI32(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_INT32;
				value.data.i32 = data;

				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUSH_I64:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				int64_t data = impl_bytecodeReadI64(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_INT64;
				value.data.i64 = data;

				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUSH_F32:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				float data = impl_bytecodeReadF32(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_FLOAT32;
				value.data.f32 = data;

				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUSH_F64:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				double data = impl_bytecodeReadF64(instruction_data);

				Empathy_Value value = {0};
				value.type.base_type = EMPATHY_VALUE_BASE_TYPE_FLOAT64;
				value.data.f64 = data;

				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUSH_ATOM:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				Empathy_Atom data = impl_bytecodeReadAtom(instruction_data);

				Empathy_Value value = {0};
				value.type = (Empathy_ValueType){EMPATHY_VALUE_BASE_TYPE_ATOM, data.type};
				value.data.atom = data;

				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_DROP:
			{
				if (yield->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				yield->head--;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_DUP:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				if (yield->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value value = yield->data[yield->head - 1];
				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_PUT:
			{
				if (yield->head >= yield->size)
					return EMPATHY_STACK_OVERFLOW;

				if (stack->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value value = stack->data[--stack->head];
				yield->data[yield->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD_TAKE:
			{
				if (stack->head >= stack->size)
					return EMPATHY_STACK_OVERFLOW;

				if (yield->head == 0)
					return EMPATHY_STACK_UNDERFLOW;

				Empathy_Value value = yield->data[--yield->head];
				stack->data[stack->head++] = value;
			}
			break;

			case EMPATHY_BYTECODE_OP_YIELD:
			{
				uint32_t data = impl_bytecodeReadU32(instruction_data);

				if (data >= layout->num_yields)
					return EMPATHY_INVALID_INSTRUCTION_DATA;

				context->yield.index = data;
				context->execution.instruction_pointer += instruction_size;
				return EMPATHY_EXECUTION_YIELD;
			}
			break;

			case EMPATHY_BYTECODE_OP_END:
			{
				context->execution.instruction_pointer += instruction_size;
				return EMPATHY_EXECUTION_END;
			}
			break;
		}

		context->execution.instruction_pointer += instruction_size;
	}

	return EMPATHY_INSTRUCTION_LIMIT_EXCEEDED;
}
