// Generated by tools/generate_bytecode.py. Do not edit manually.
export const EMPATHY_BYTECODE_VERSION_MAJOR = 1;
export const EMPATHY_BYTECODE_VERSION_MINOR = 0;
export const EMPATHY_BYTECODE_VERSION = 0x00010000;

export const EmpathyBytecodeOperandSize = {
    U8: 1,
    U16: 2,
    U32: 4,
    U64: 8,
    I8: 1,
    I16: 2,
    I32: 4,
    I64: 8,
    F32: 4,
    F64: 8,
    ATOM: 8,
    PARAMETER_INDEX: 4,
    YIELD_INDEX: 4,
    PROGRAM_OFFSET: 8,
} as const;

export const EmpathyBytecodeOpcode = {
    PUSH_U8: 0x00,
    PUSH_U16: 0x01,
    PUSH_U32: 0x02,
    PUSH_U64: 0x03,
    PUSH_I8: 0x04,
    PUSH_I16: 0x05,
    PUSH_I32: 0x06,
    PUSH_I64: 0x07,
    PUSH_F32: 0x08,
    PUSH_F64: 0x09,
    PUSH_ATOM: 0x0A,
    LOAD: 0x0B,
    STORE: 0x0C,
    DROP: 0x0D,
    DUP: 0x0E,
    ADD: 0x0F,
    SUB: 0x10,
    MUL: 0x11,
    DIV: 0x12,
    EQUAL: 0x13,
    NOT_EQUAL: 0x14,
    LESS: 0x15,
    LESS_EQUAL: 0x16,
    GREATER: 0x17,
    GREATER_EQUAL: 0x18,
    JUMP: 0x19,
    JUMP_FALSE: 0x1A,
    JUMP_TRUE: 0x1B,
    REJECT: 0x1C,
    REJECT_FALSE: 0x1D,
    REJECT_TRUE: 0x1E,
    MATCH: 0x1F,
    YIELD_PUSH_U8: 0x20,
    YIELD_PUSH_U16: 0x21,
    YIELD_PUSH_U32: 0x22,
    YIELD_PUSH_U64: 0x23,
    YIELD_PUSH_I8: 0x24,
    YIELD_PUSH_I16: 0x25,
    YIELD_PUSH_I32: 0x26,
    YIELD_PUSH_I64: 0x27,
    YIELD_PUSH_F32: 0x28,
    YIELD_PUSH_F64: 0x29,
    YIELD_PUSH_ATOM: 0x2A,
    YIELD_DROP: 0x2B,
    YIELD_DUP: 0x2C,
    YIELD_PUT: 0x2D,
    YIELD_TAKE: 0x2E,
    YIELD: 0x2F,
    END: 0x30,
} as const;

export const EmpathyBytecodeInstructionSize = {
    PUSH_U8: 2,
    PUSH_U16: 3,
    PUSH_U32: 5,
    PUSH_U64: 9,
    PUSH_I8: 2,
    PUSH_I16: 3,
    PUSH_I32: 5,
    PUSH_I64: 9,
    PUSH_F32: 5,
    PUSH_F64: 9,
    PUSH_ATOM: 9,
    LOAD: 5,
    STORE: 5,
    DROP: 1,
    DUP: 1,
    ADD: 1,
    SUB: 1,
    MUL: 1,
    DIV: 1,
    EQUAL: 1,
    NOT_EQUAL: 1,
    LESS: 1,
    LESS_EQUAL: 1,
    GREATER: 1,
    GREATER_EQUAL: 1,
    JUMP: 9,
    JUMP_FALSE: 9,
    JUMP_TRUE: 9,
    REJECT: 1,
    REJECT_FALSE: 1,
    REJECT_TRUE: 1,
    MATCH: 1,
    YIELD_PUSH_U8: 2,
    YIELD_PUSH_U16: 3,
    YIELD_PUSH_U32: 5,
    YIELD_PUSH_U64: 9,
    YIELD_PUSH_I8: 2,
    YIELD_PUSH_I16: 3,
    YIELD_PUSH_I32: 5,
    YIELD_PUSH_I64: 9,
    YIELD_PUSH_F32: 5,
    YIELD_PUSH_F64: 9,
    YIELD_PUSH_ATOM: 9,
    YIELD_DROP: 1,
    YIELD_DUP: 1,
    YIELD_PUT: 1,
    YIELD_TAKE: 1,
    YIELD: 5,
    END: 1,
} as const;

export class BytecodeWriter {
    private readonly data: number[] = [];

    get offset(): number {
        return this.data.length;
    }

    private unsignedBytes(value: number, maximum: number, size: number, label: string): number[] {
        if (!Number.isInteger(value) || value < 0 || value > maximum) {
            throw new Error(`Value is not a ${label}: ${value}`);
        }
        const bytes: number[] = [];
        for (let byte = 0; byte < size; ++byte) {
            bytes.push(value % 0x100);
            value = Math.floor(value / 0x100);
        }
        return bytes;
    }

    private uint64Bytes(value: number | bigint): number[] {
        const integer = typeof value === "bigint"
            ? value
            : Number.isSafeInteger(value) ? BigInt(value) : -1n;
        if (integer < 0n || integer > 0xFFFFFFFFFFFFFFFFn) {
            throw new Error(`Value is not a uint64: ${value}`);
        }
        return Array.from({ length: 8 }, (_, byte) =>
            Number((integer >> BigInt(byte * 8)) & 0xFFn));
    }

    u8(value: number): void {
        this.data.push(...this.unsignedBytes(value, 0xFF, 1, "uint8"));
    }

    u16(value: number): void {
        this.data.push(...this.unsignedBytes(value, 0xFFFF, 2, "uint16"));
    }

    u32(value: number): void {
        this.data.push(...this.unsignedBytes(value, 0xFFFFFFFF, 4, "uint32"));
    }

    u64(value: number | bigint): void {
        this.data.push(...this.uint64Bytes(value));
    }

    atom(type: number, value: number): void {
        const typeBytes = this.unsignedBytes(type, 0xFFFFFFFF, 4, "uint32");
        const valueBytes = this.unsignedBytes(value, 0xFFFFFFFF, 4, "uint32");
        this.data.push(...typeBytes, ...valueBytes);
    }

    opcode(value: number): void {
        this.u8(value);
    }

    patchU64(offset: number, value: number | bigint): void {
        if (!Number.isInteger(offset) || offset < 0 || offset + 8 > this.data.length) {
            throw new Error(`Invalid uint64 patch offset: ${offset}`);
        }
        const bytes = this.uint64Bytes(value);
        for (let byte = 0; byte < bytes.length; ++byte) this.data[offset + byte] = bytes[byte];
    }

    finish(): Uint8Array {
        return Uint8Array.from(this.data);
    }
}
