#pragma once

#include <stdint.h> // TODO: get rid of this dependency later

// Version
#define EMPATHY_VERSION_MAJOR 1
#define EMPATHY_VERSION_MINOR 0
#define EMPATHY_VERSION_PATCH 0
#define EMPATHY_VERSION "1.0.0-dev"

// BEGIN GENERATED: EMPATHY BYTECODE DEFINES
// Generated by tools/generate_bytecode.py. Do not edit manually.
#define EMPATHY_BYTECODE_VERSION_MAJOR 1u
#define EMPATHY_BYTECODE_VERSION_MINOR 0u
#define EMPATHY_BYTECODE_MAKE_VERSION(MAJOR, MINOR) (((uint32_t)(MAJOR) << 16u) | (uint32_t)(MINOR))
#define EMPATHY_BYTECODE_VERSION EMPATHY_BYTECODE_MAKE_VERSION(EMPATHY_BYTECODE_VERSION_MAJOR, EMPATHY_BYTECODE_VERSION_MINOR)
// END GENERATED: EMPATHY BYTECODE DEFINES

// Platform specific defines
#if defined(_WIN32)
	#define EMPATHY_EXPORT		__declspec(dllexport)
	#define EMPATHY_IMPORT		__declspec(dllimport)
	#define EMPATHY_INLINE		__forceinline
	#define EMPATHY_RESTRICT	__restrict
#else
	#define EMPATHY_EXPORT		__attribute__((visibility("default")))
	#define EMPATHY_IMPORT
	#define EMPATHY_INLINE		__inline__
	#define EMPATHY_RESTRICT	__restrict
#endif

#if defined(EMPATHY_SHARED_LIBRARY)
	#define EMPATHY_APIENTRY extern EMPATHY_EXPORT
#else
	#define EMPATHY_APIENTRY extern EMPATHY_IMPORT
#endif

#if !defined(EMPATHY_NULL_HANDLE)
	#define EMPATHY_NULL_HANDLE 0
#endif

#define EMPATHY_DEFINE_HANDLE(TYPE) typedef uint64_t TYPE
#define EMPATHY_PROGRAM_OFFSET_NONE UINT64_MAX

#ifdef __cplusplus
extern "C" {
#endif

// Opaque handles
EMPATHY_DEFINE_HANDLE(Empathy_Instance);
EMPATHY_DEFINE_HANDLE(Empathy_ProgramLayout);
EMPATHY_DEFINE_HANDLE(Empathy_Program);
EMPATHY_DEFINE_HANDLE(Empathy_Machine);

// Enums
typedef enum Empathy_Result_t
{
	EMPATHY_SUCCESS = 0,
	EMPATHY_EXECUTION_YIELD,
	EMPATHY_EXECUTION_END,
	EMPATHY_PREDICATE_MATCHED,
	EMPATHY_PREDICATE_REJECTED,
	EMPATHY_NOT_IMPLEMENTED,
	EMPATHY_INVALID_INSTANCE,
	EMPATHY_INVALID_OUTPUT_ARGUMENT,
	EMPATHY_UNSUPPORTED_BYTECODE_VERSION,
	EMPATHY_INVALID_INSTRUCTION_OPCODE,
	EMPATHY_INVALID_INSTRUCTION_DATA,
	EMPATHY_INVALID_OPERAND_TYPE,
	EMPATHY_INVALID_RESUME_STATE,
	EMPATHY_MACHINE_NOT_YIELDED,
	EMPATHY_PROGRAM_NOT_BOUND,
	EMPATHY_PROGRAM_ENTRY_POINT_NOT_BOUND,
	EMPATHY_PROGRAM_OUT_OF_BOUNDS_READ,
	EMPATHY_PARAMETER_NOT_READABLE,
	EMPATHY_PARAMETER_NOT_WRITABLE,
	EMPATHY_PARAMETER_TABLE_OUT_OF_BOUNDS_READ,
	EMPATHY_PARAMETER_TABLE_OUT_OF_BOUNDS_WRITE,
	EMPATHY_BASE_TYPE_MISMATCH,
	EMPATHY_ATOM_TYPE_MISMATCH,
	EMPATHY_STACK_OVERFLOW,
	EMPATHY_STACK_UNDERFLOW,
	EMPATHY_INSTRUCTION_LIMIT_EXCEEDED,

	// FIXME: add more error codes for internal errors
	EMPATHY_INTERNAL_ERROR,

	EMPATHY_RESULT_ENUM_MAX,
	EMPATHY_RESULT_ENUM_FORCE32 = 0x7FFFFFFF,
} Empathy_Result;

typedef enum Empathy_ValueBaseType_t
{
	EMPATHY_VALUE_BASE_TYPE_UINT8 = 0,
	EMPATHY_VALUE_BASE_TYPE_UINT16,
	EMPATHY_VALUE_BASE_TYPE_UINT32,
	EMPATHY_VALUE_BASE_TYPE_UINT64,
	EMPATHY_VALUE_BASE_TYPE_INT8,
	EMPATHY_VALUE_BASE_TYPE_INT16,
	EMPATHY_VALUE_BASE_TYPE_INT32,
	EMPATHY_VALUE_BASE_TYPE_INT64,
	EMPATHY_VALUE_BASE_TYPE_FLOAT32,
	EMPATHY_VALUE_BASE_TYPE_FLOAT64,
	EMPATHY_VALUE_BASE_TYPE_ATOM,

	EMPATHY_VALUE_BASE_TYPE_ENUM_MAX,
	EMPATHY_VALUE_BASE_TYPE_ENUM_FORCE32 = 0x7FFFFFFF,
} Empathy_ValueBaseType;

typedef enum Empathy_ParameterAccessFlags_t
{
	EMPATHY_PARAMETER_ACCESS_FLAGS_READ = 0x00000001,
	EMPATHY_PARAMETER_ACCESS_FLAGS_WRITE = 0x00000002,
	EMPATHY_PARAMETER_ACCESS_FLAGS_READ_WRITE = 0x00000003,

	EMPATHY_PARAMETER_ACCESS_FLAGS_ENUM_FORCE32 = 0x7FFFFFFF,
} Empathy_ParameterAccessFlags;

// BEGIN GENERATED: EMPATHY BYTECODE OPCODES
// Generated by tools/generate_bytecode.py. Do not edit manually.
typedef enum Empathy_BytecodeOpcode_t
{
	EMPATHY_BYTECODE_OP_PUSH_U8 = 0x00,
	EMPATHY_BYTECODE_OP_PUSH_U16 = 0x01,
	EMPATHY_BYTECODE_OP_PUSH_U32 = 0x02,
	EMPATHY_BYTECODE_OP_PUSH_U64 = 0x03,
	EMPATHY_BYTECODE_OP_PUSH_I8 = 0x04,
	EMPATHY_BYTECODE_OP_PUSH_I16 = 0x05,
	EMPATHY_BYTECODE_OP_PUSH_I32 = 0x06,
	EMPATHY_BYTECODE_OP_PUSH_I64 = 0x07,
	EMPATHY_BYTECODE_OP_PUSH_F32 = 0x08,
	EMPATHY_BYTECODE_OP_PUSH_F64 = 0x09,
	EMPATHY_BYTECODE_OP_PUSH_ATOM = 0x0A,
	EMPATHY_BYTECODE_OP_LOAD = 0x0B,
	EMPATHY_BYTECODE_OP_STORE = 0x0C,
	EMPATHY_BYTECODE_OP_DROP = 0x0D,
	EMPATHY_BYTECODE_OP_DUP = 0x0E,
	EMPATHY_BYTECODE_OP_ADD = 0x0F,
	EMPATHY_BYTECODE_OP_SUB = 0x10,
	EMPATHY_BYTECODE_OP_MUL = 0x11,
	EMPATHY_BYTECODE_OP_DIV = 0x12,
	EMPATHY_BYTECODE_OP_EQUAL = 0x13,
	EMPATHY_BYTECODE_OP_NOT_EQUAL = 0x14,
	EMPATHY_BYTECODE_OP_LESS = 0x15,
	EMPATHY_BYTECODE_OP_LESS_EQUAL = 0x16,
	EMPATHY_BYTECODE_OP_GREATER = 0x17,
	EMPATHY_BYTECODE_OP_GREATER_EQUAL = 0x18,
	EMPATHY_BYTECODE_OP_JUMP = 0x19,
	EMPATHY_BYTECODE_OP_JUMP_FALSE = 0x1A,
	EMPATHY_BYTECODE_OP_JUMP_TRUE = 0x1B,
	EMPATHY_BYTECODE_OP_REJECT = 0x1C,
	EMPATHY_BYTECODE_OP_REJECT_FALSE = 0x1D,
	EMPATHY_BYTECODE_OP_REJECT_TRUE = 0x1E,
	EMPATHY_BYTECODE_OP_MATCH = 0x1F,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_U8 = 0x20,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_U16 = 0x21,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_U32 = 0x22,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_U64 = 0x23,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_I8 = 0x24,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_I16 = 0x25,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_I32 = 0x26,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_I64 = 0x27,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_F32 = 0x28,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_F64 = 0x29,
	EMPATHY_BYTECODE_OP_YIELD_PUSH_ATOM = 0x2A,
	EMPATHY_BYTECODE_OP_YIELD_DROP = 0x2B,
	EMPATHY_BYTECODE_OP_YIELD_DUP = 0x2C,
	EMPATHY_BYTECODE_OP_YIELD_PUT = 0x2D,
	EMPATHY_BYTECODE_OP_YIELD_TAKE = 0x2E,
	EMPATHY_BYTECODE_OP_YIELD = 0x2F,
	EMPATHY_BYTECODE_OP_END = 0x30,

	EMPATHY_BYTECODE_OP_ENUM_MAX = 49,
	EMPATHY_BYTECODE_OP_ENUM_FORCE32 = 0x7FFFFFFF,
} Empathy_BytecodeOpcode;
// END GENERATED: EMPATHY BYTECODE OPCODES

// Structs
typedef struct Empathy_InstanceDesc_t
{
	uint32_t reserved;
	// TODO: allocator context
	// TOOD: flags?
} Empathy_InstanceDesc;

typedef struct Empathy_Atom_t
{
	uint32_t type;
	uint32_t value;
} Empathy_Atom;

typedef struct Empathy_ValueType_t
{
	Empathy_ValueBaseType base_type;
	uint32_t atom_type;
} Empathy_ValueType;

typedef union Empathy_ValueData_t
{
	uint8_t u8;
	uint16_t u16;
	uint32_t u32;
	uint64_t u64;
	int8_t i8;
	int16_t i16;
	int32_t i32;
	int64_t i64;
	float f32;
	double f64;
	Empathy_Atom atom;
} Empathy_ValueData;

typedef struct Empathy_Value
{
	Empathy_ValueType type;
	Empathy_ValueData data;
} Empathy_Value;

typedef struct Empathy_AtomTypeDesc_t
{
	uint32_t type;
	uint32_t min_value;
	uint32_t max_value;
} Empathy_AtomTypeDesc;

typedef struct Empathy_ParameterDesc_t
{
	uint32_t table;

	Empathy_ValueType type;
	Empathy_ParameterAccessFlags access;

	uint64_t offset;
} Empathy_ParameterDesc;

typedef struct Empathy_YieldDesc
{
	uint32_t num_resume_values;
	const Empathy_ValueType *resume_value_types;
} Empathy_YieldDesc;

typedef struct Empathy_ProgramLayoutDesc_t
{
	uint32_t num_atom_types;
	const Empathy_AtomTypeDesc *atom_types;

	uint32_t num_parameters;
	const Empathy_ParameterDesc *parameters;

	uint32_t num_yields;
	const Empathy_YieldDesc *yields;
} Empathy_ProgramLayoutDesc;

typedef struct Empathy_EntryPointDesc_t
{
	uint64_t execution_offset;
	uint64_t predicate_offset;
} Empathy_EntryPointDesc;

typedef struct Empathy_ProgramDesc_t
{
	Empathy_ProgramLayout layout;

	uint32_t num_entry_points;
	const Empathy_EntryPointDesc *entry_points;

	uint32_t bytecode_version;
	uint64_t bytecode_size;
	const void *bytecode_data;
} Empathy_ProgramDesc;

typedef struct Empathy_MachineDesc_t
{
	uint32_t execution_stack_size;
	uint32_t yield_stack_size;
	uint32_t predicate_stack_size;
	uint32_t max_parameter_tables;
	uint32_t instruction_limit;
} Empathy_MachineDesc;

typedef struct Empathy_MatchResult_t
{
	Empathy_Value value;
	uint32_t entry_point_index;
} Empathy_MatchResult;

// Function pointers
typedef Empathy_Result (*PFN_empathyCreateProgramLayout)(Empathy_Instance instance, const Empathy_ProgramLayoutDesc *desc, Empathy_ProgramLayout *layout);
typedef Empathy_Result (*PFN_empathyCreateProgram)(Empathy_Instance instance, const Empathy_ProgramDesc *desc, Empathy_Program *program);
typedef Empathy_Result (*PFN_empathyCreateMachine)(Empathy_Instance instance, const Empathy_MachineDesc *desc, Empathy_Machine *machine);

typedef Empathy_Result (*PFN_empathyDestroyProgramLayout)(Empathy_Instance instance, Empathy_ProgramLayout layout);
typedef Empathy_Result (*PFN_empathyDestroyProgram)(Empathy_Instance instance, Empathy_Program program);
typedef Empathy_Result (*PFN_empathyDestroyMachine)(Empathy_Instance instance, Empathy_Machine machine);
typedef Empathy_Result (*PFN_empathyDestroyInstance)(Empathy_Instance instance);

typedef Empathy_Result (*PFN_empathyBindProgram)(Empathy_Instance instance, Empathy_Machine machine, Empathy_Program program);
typedef Empathy_Result (*PFN_empathyBindProgramEntryPoint)(Empathy_Instance instance, Empathy_Machine machine, uint32_t index);
typedef Empathy_Result (*PFN_empathyBindParameterTable)(Empathy_Instance instance, Empathy_Machine machine, uint32_t index, uint64_t size, void *data);

typedef Empathy_Result (*PFN_empathyRun)(Empathy_Instance instance, Empathy_Machine machine);
typedef Empathy_Result (*PFN_empathyMatch)(Empathy_Instance instance, Empathy_Machine machine, uint32_t max_count, Empathy_MatchResult *results, uint32_t *result_count);

typedef Empathy_Result (*PFN_empathyGetYieldStackSize)(Empathy_Instance instance, Empathy_Machine machine, uint32_t *size);
typedef Empathy_Result (*PFN_empathyGetYieldIndex)(Empathy_Instance instance, Empathy_Machine machine, uint32_t *index);
typedef Empathy_Result (*PFN_empathyYieldStackPush)(Empathy_Instance instance, Empathy_Machine machine, Empathy_Value value);
typedef Empathy_Result (*PFN_empathyYieldStackPop)(Empathy_Instance instance, Empathy_Machine machine, Empathy_Value *value);
typedef Empathy_Result (*PFN_empathyYieldStackPeek)(Empathy_Instance instance, Empathy_Machine machine, uint32_t depth, Empathy_Value *value);


typedef struct Empathy_InstanceTable_t
{
	PFN_empathyCreateProgramLayout createProgramLayout;
	PFN_empathyCreateProgram createProgram;
	PFN_empathyCreateMachine createMachine;

	PFN_empathyDestroyProgramLayout destroyProgramLayout;
	PFN_empathyDestroyProgram destroyProgram;
	PFN_empathyDestroyMachine destroyMachine;
	PFN_empathyDestroyInstance destroyInstance;

	PFN_empathyBindProgram bindProgram;
	PFN_empathyBindProgramEntryPoint bindProgramEntryPoint;
	PFN_empathyBindParameterTable bindParameterTable;

	PFN_empathyRun run;
	PFN_empathyMatch match;

	PFN_empathyGetYieldStackSize getYieldStackSize;
	PFN_empathyGetYieldIndex getYieldIndex;
	PFN_empathyYieldStackPush yieldStackPush;
	PFN_empathyYieldStackPop yieldStackPop;
	PFN_empathyYieldStackPeek yieldStackPeek;
} Empathy_InstanceTable;

// API
#if !defined(EMPATHY_NO_PROTOTYPES)
EMPATHY_APIENTRY Empathy_Result empathyCreateInstance(const Empathy_InstanceDesc *desc, Empathy_Instance* instance);
EMPATHY_APIENTRY Empathy_Result empathyGetInstanceTable(Empathy_Instance instance, Empathy_InstanceTable *instance_table);

EMPATHY_APIENTRY Empathy_Result empathyCreateProgramLayout(Empathy_Instance instance, const Empathy_ProgramLayoutDesc *desc, Empathy_ProgramLayout *layout);
EMPATHY_APIENTRY Empathy_Result empathyCreateProgram(Empathy_Instance instance, const Empathy_ProgramDesc *desc, Empathy_Program *program);
EMPATHY_APIENTRY Empathy_Result empathyCreateMachine(Empathy_Instance instance, const Empathy_MachineDesc *desc, Empathy_Machine *machine);

EMPATHY_APIENTRY Empathy_Result empathyDestroyProgramLayout(Empathy_Instance instance, Empathy_ProgramLayout layout);
EMPATHY_APIENTRY Empathy_Result empathyDestroyProgram(Empathy_Instance instance, Empathy_Program program);
EMPATHY_APIENTRY Empathy_Result empathyDestroyMachine(Empathy_Instance instance, Empathy_Machine machine);
EMPATHY_APIENTRY Empathy_Result empathyDestroyInstance(Empathy_Instance instance);

EMPATHY_APIENTRY Empathy_Result empathyBindProgram(Empathy_Instance instance, Empathy_Machine machine, Empathy_Program program);
EMPATHY_APIENTRY Empathy_Result empathyBindProgramEntryPoint(Empathy_Instance instance, Empathy_Machine machine, uint32_t index);
EMPATHY_APIENTRY Empathy_Result empathyBindParameterTable(Empathy_Instance instance, Empathy_Machine machine, uint32_t index, uint64_t size, void *data);

EMPATHY_APIENTRY Empathy_Result empathyRun(Empathy_Instance instance, Empathy_Machine machine);
EMPATHY_APIENTRY Empathy_Result empathyMatch(Empathy_Instance instance, Empathy_Machine machine, uint32_t max_count, Empathy_MatchResult *results, uint32_t *result_count);

EMPATHY_APIENTRY Empathy_Result empathyGetYieldStackSize(Empathy_Instance instance, Empathy_Machine machine, uint32_t *size);
EMPATHY_APIENTRY Empathy_Result empathyGetYieldIndex(Empathy_Instance instance, Empathy_Machine machine, uint32_t *index);
EMPATHY_APIENTRY Empathy_Result empathyYieldStackPush(Empathy_Instance instance, Empathy_Machine machine, Empathy_Value value);
EMPATHY_APIENTRY Empathy_Result empathyYieldStackPop(Empathy_Instance instance, Empathy_Machine machine, Empathy_Value *value);
EMPATHY_APIENTRY Empathy_Result empathyYieldStackPeek(Empathy_Instance instance, Empathy_Machine machine, uint32_t depth, Empathy_Value *value);
#endif

#ifdef __cplusplus
}
#endif
