#!/usr/bin/env python3
import argparse
import json
import sys

from pathlib import Path

def load_spec(path: Path) -> dict:
    spec = json.loads(path.read_text(encoding="utf-8"))
    if spec.get("endianness") != "little":
        raise ValueError("Only little-endian bytecode is supported")
    if spec.get("instructionAlignment") != 1:
        raise ValueError("Bytecode instructions must be byte-aligned")

    operand_sizes = spec.get("operandSizes", {})
    if not operand_sizes:
        raise ValueError("Bytecode spec must define operand sizes")
    for operand, size in operand_sizes.items():
        if not operand or type(size) is not int or size <= 0 or size > 255:
            raise ValueError(f"Invalid size for operand type: {operand}")

    mode_bits = spec.get("modeBits", {})
    if not mode_bits:
        raise ValueError("Bytecode spec must define mode bits")

    used_mode_bits = 0
    for mode, bit in mode_bits.items():
        if not mode or type(bit) is not int or bit <= 0 or bit > 0x80 or bit & (bit - 1):
            raise ValueError(f"Invalid bit for instruction mode: {mode}")
        if used_mode_bits & bit:
            raise ValueError(f"Duplicate bit for instruction mode: {mode}")
        used_mode_bits |= bit

    instructions = spec.get("instructions", [])
    opcodes = [instruction["opcode"] for instruction in instructions]
    if opcodes != list(range(len(instructions))):
        raise ValueError("Opcodes must be unique, contiguous, and sorted from zero")
    if len(instructions) > 256:
        raise ValueError("A bytecode opcode must fit in one byte")

    names = set()
    for instruction in instructions:
        name = instruction["name"]
        if name in names:
            raise ValueError(f"Duplicate instruction name: {name}")
        names.add(name)

        for operand in instruction["operands"]:
            if operand not in operand_sizes:
                raise ValueError(f"Unknown operand type: {operand}")
        if 1 + sum(operand_sizes[operand] for operand in instruction["operands"]) > 255:
            raise ValueError(f"Instruction is too large: {name}")

        if not instruction["modes"]:
            raise ValueError(f"Instruction must support at least one mode: {name}")
        for mode in instruction["modes"]:
            if mode not in mode_bits:
                raise ValueError(f"Unknown instruction mode: {mode}")
        if len(set(instruction["modes"])) != len(instruction["modes"]):
            raise ValueError(f"Duplicate instruction mode: {name}")

    return spec

def generate_c_opcode_constant(name: str) -> str:
    return "EMPATHY_BYTECODE_OP_" + name.upper()

def generate_c_public_defines(spec: dict) -> str:
    version = spec["version"]
    lines = [
        "// Generated by tools/generate_bytecode.py. Do not edit manually.",
        f"#define EMPATHY_BYTECODE_VERSION_MAJOR {version['major']}u",
        f"#define EMPATHY_BYTECODE_VERSION_MINOR {version['minor']}u",
        "#define EMPATHY_BYTECODE_MAKE_VERSION(MAJOR, MINOR) (((uint32_t)(MAJOR) << 16u) | (uint32_t)(MINOR))",
        "#define EMPATHY_BYTECODE_VERSION EMPATHY_BYTECODE_MAKE_VERSION(EMPATHY_BYTECODE_VERSION_MAJOR, EMPATHY_BYTECODE_VERSION_MINOR)",
        "",
    ]
    return "\n".join(lines)

def generate_c_public_opcodes(spec: dict) -> str:
    instructions = spec["instructions"]
    lines = [
        "// Generated by tools/generate_bytecode.py. Do not edit manually.",
        "typedef enum Empathy_BytecodeOpcode_t",
        "{",
    ]

    for instruction in instructions:
        lines.append(f"\t{generate_c_opcode_constant(instruction['name'])} = 0x{instruction['opcode']:02X},")

    lines.extend([
        "",
        f"\tEMPATHY_BYTECODE_OP_ENUM_MAX = {len(instructions)},",
        "\tEMPATHY_BYTECODE_OP_ENUM_FORCE32 = 0x7FFFFFFF,",
        "} Empathy_BytecodeOpcode;",
        "",
    ])
    return "\n".join(lines)

def generate_c_internal_section(spec: dict) -> str:
    instructions = spec["instructions"]
    operand_sizes = spec["operandSizes"]
    mode_bits = spec["modeBits"]
    sizes = [1 + sum(operand_sizes[operand] for operand in instruction["operands"]) for instruction in instructions]
    modes = [sum(mode_bits[mode] for mode in instruction["modes"]) for instruction in instructions]

    def values(items):
        return ["\t" + ", ".join(str(value) for value in items[index:index + 12]) + "," for index in range(0, len(items), 12)]

    lines = [
        "// Generated by tools/generate_bytecode.py. Do not edit manually.",
        "static const uint8_t impl_bytecode_instruction_sizes[EMPATHY_BYTECODE_OP_ENUM_MAX] =",
        "{",
        *values(sizes),
        "};",
        "",
        "static const uint8_t impl_bytecode_instruction_modes[EMPATHY_BYTECODE_OP_ENUM_MAX] =",
        "{",
        *values(modes),
        "};",
        "",
    ]
    return "\n".join(lines)

def generate_typescript(spec: dict) -> str:
    version = spec["version"]
    operand_sizes = spec["operandSizes"]
    instructions = spec["instructions"]
    packed_version = (version["major"] << 16) | version["minor"]
    lines = [
        "// Generated by tools/generate_bytecode.py. Do not edit manually.",
        f"export const EMPATHY_BYTECODE_VERSION_MAJOR = {version['major']};",
        f"export const EMPATHY_BYTECODE_VERSION_MINOR = {version['minor']};",
        f"export const EMPATHY_BYTECODE_VERSION = 0x{packed_version:08X};",
        "",
        "export const EmpathyBytecodeOperandSize = {",
    ]
    for operand, size in operand_sizes.items():
        lines.append(f"    {operand.upper()}: {size},")

    lines.extend(["} as const;", "", "export const EmpathyBytecodeOpcode = {"])
    for instruction in instructions:
        lines.append(f"    {instruction['name'].upper()}: 0x{instruction['opcode']:02X},")

    lines.extend(["} as const;", "", "export const EmpathyBytecodeInstructionSize = {"])
    for instruction in instructions:
        size = 1 + sum(operand_sizes[operand] for operand in instruction["operands"])
        lines.append(f"    {instruction['name'].upper()}: {size},")

    writer = Path(__file__).with_name("bytecode_writer.ts.in").read_text(encoding="utf-8")
    lines.extend(["} as const;", "", writer.rstrip(), ""])
    return "\n".join(lines)

def update_region(path: Path, name: str, content: str, check: bool) -> bool:
    begin_marker = f"// BEGIN GENERATED: {name}"
    end_marker = f"// END GENERATED: {name}"
    current = path.read_text(encoding="utf-8").replace("\r\n", "\n")

    begin = current.find(begin_marker)
    end = current.find(end_marker, begin + len(begin_marker))
    if begin < 0 or end < 0:
        raise ValueError(f"Generated region '{name}' not found in {path}")
    if current.find(begin_marker, begin + len(begin_marker)) >= 0 or current.find(end_marker, end + len(end_marker)) >= 0:
        raise ValueError(f"Generated region '{name}' occurs more than once in {path}")

    replacement = begin_marker + "\n" + content.rstrip("\n") + "\n" + end_marker
    expected = current[:begin] + replacement + current[end + len(end_marker):]
    if check:
        if current != expected:
            print(f"Generated region is out of date: {path} ({name})", file=sys.stderr)
            return False
        return True

    with path.open("w", encoding="utf-8", newline="\n") as output:
        output.write(expected)
    return True

def update_file(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else None
    expected = content.rstrip("\n") + "\n"
    if check:
        if current != expected:
            print(f"Generated file is out of date: {path}", file=sys.stderr)
            return False
        return True

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as output:
        output.write(expected)
    return True

def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Empathy bytecode ABI artifacts")
    parser.add_argument("spec", type=Path, help="Path to an Empathy bytecode JSON specification")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are out of date")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    spec = load_spec(args.spec.resolve())

    success = update_region(root / "include" / "empathy.h", "EMPATHY BYTECODE DEFINES", generate_c_public_defines(spec), args.check)
    success = update_region(root / "include" / "empathy.h", "EMPATHY BYTECODE OPCODES", generate_c_public_opcodes(spec), args.check) and success
    success = update_region(root / "src" / "impl" / "impl_bytecode.c", "EMPATHY BYTECODE TABLES", generate_c_internal_section(spec), args.check) and success
    success = update_file(root / "plugins" / "obsidian" / "src" / "bytecode.ts", generate_typescript(spec), args.check) and success

    return 0 if success else 1

if __name__ == "__main__":
    raise SystemExit(main())
